server:
  port: 8080

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2018/12/12
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - wangwu
#  dog:
#    name: xiaogou
#    age: 2