server:
  port: 8070

person:
  lastName: zhangsan@qq.com${random.uuid} #lastName = last-name
  age: ${random.int}
  boss: false
  birth: 2018/12/12
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - wangwu
  dog:
    name: xiaogou
    age: 2